language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "36c6a624-b008-4d94-905b-ceee5b74a367"
  app: bloggernj
